### ISSUE TITLE
Annex_Panel_2020_Clips_and_Hinges  disappeared.

### ISSUE THREAD

**Issue by thinker2013** [Annex-Engineering/Annex-Engineering_User_Mods#82]
Can you supply this mods  again?

Annex_Panel_2020_Clips_and_Hinges
[thanks](https://github.com/Annex-Engineering/Other_Printer_Mods/tree/master/All_Printers/Annex_Panel_2020_Clips_and_Hinges)

**Comment by Trails5000** [comment]
https://github.com/Annex-Engineering/Annex-Engineering_User_Mods/tree/main/Printers/All_Printers/annex_dev-Panel_2020_Clips_and_Hinges
